// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rpgGame.Data;

#nullable disable

namespace rpgGame.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814101357_AddPasswordToForum")]
    partial class AddPasswordToForum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("rpgGame.Models.EventsData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Affect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Person")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Porm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Talk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EventsDatas");
                });

            modelBuilder.Entity("rpgGame.Models.ForumMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ForumMessages");
                });

            modelBuilder.Entity("rpgGame.Models.ItemData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Able")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Porm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ItemDatas");
                });

            modelBuilder.Entity("rpgGame.Models.JobData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MagicAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MagicDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("JobDatas");
                });

            modelBuilder.Entity("rpgGame.Models.MonsterData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MagicAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MagicDefense")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonsterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Mp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Skill1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Skill2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Skill3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Skill4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Skill5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MonsterDatas");
                });

            modelBuilder.Entity("rpgGame.Models.NatureData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NatureName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NatureDatas");
                });

            modelBuilder.Entity("rpgGame.Models.StatusData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StatusDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
